const V2_CONFIG = Object.freeze({
  APP_NAME: '학생관리시스템 V2 API',
  API_VERSION: 'v1',
  ADMIN_REGISTRY_SPREADSHEET_ID: '14UljkUze6SSG8nIu8oC5LWTdI30fwNTOJQo0ERCytaE',
  SESSION_TTL_SECONDS: 21600,
  PASSWORD_HASH_ROUNDS: 1200,
  ADMIN_TEACHER_ID: 'T-ADMIN-001'
});
